# Generated by Django 2.0.1 on 2018-01-11 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arc',
            name='image',
            field=models.FileField(blank=True, max_length=250, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.FileField(blank=True, max_length=250, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='character',
            name='thumb',
            field=models.FileField(blank=True, max_length=250, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='creator',
            name='image',
            field=models.FileField(blank=True, max_length=250, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='creator',
            name='thumb',
            field=models.FileField(blank=True, max_length=250, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='cover',
            field=models.FileField(blank=True, max_length=250, upload_to='images/', verbose_name='Cover Image'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='thumb',
            field=models.FileField(blank=True, max_length=250, upload_to='images/', verbose_name='Thumbnail Image'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='logo',
            field=models.FileField(blank=True, max_length=250, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.FileField(blank=True, max_length=250, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='thumb',
            field=models.FileField(blank=True, max_length=250, upload_to='images/'),
        ),
    ]
