# Generated by Django 2.0 on 2017-12-03 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Settings',
        ),
    ]
