# Generated by Django 2.0.1 on 2018-01-12 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0002_increase_field_lengths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='name',
            field=models.CharField(blank=True, max_length=350, verbose_name='Issue Name'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='slug',
            field=models.SlugField(max_length=350, unique=True),
        ),
    ]
