# Generated by Django 2.0 on 2017-12-06 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0002_delete_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arc',
            options={'ordering': ['name'], 'verbose_name_plural': 'Arcs'},
        ),
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['name'], 'verbose_name_plural': 'Characters'},
        ),
        migrations.AlterModelOptions(
            name='creator',
            options={'ordering': ['name'], 'verbose_name_plural': 'Creators'},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'ordering': ['name'], 'verbose_name_plural': 'Publishers'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name'], 'verbose_name_plural': 'Teams'},
        ),
    ]
