# Generated by Django 2.0 on 2017-12-07 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0003_add_model_ordering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arc',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='creator',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name']},
        ),
    ]
