# Generated by Django 2.0.1 on 2018-01-13 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0003_increase_field_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roles',
            options={'ordering': ['creator__name'], 'verbose_name_plural': 'Roles'},
        ),
    ]
