# Generated by Django 2.0.1 on 2018-01-20 00:05

from django.db import migrations, models

ROLE_CHOICES = (
    'Artist',
    'Colorist',
    'Cover',
    'Editor',
    'Inker',
    'Journalist',
    'Letterer',
    'Other',
    'Penciler',
    'Production',
    'Writer',
)


def add_role_data(apps, schema_editor):
    Role = apps.get_model('comics', 'Role')
    for role in ROLE_CHOICES:
        Role.objects.create(name=role)


def remove_role_data(apps, schema_editor):
    Role = apps.get_model('comics', 'Role')
    Role.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0004_order_roles_by_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.RunPython(
            add_role_data,
            remove_role_data
        ),
    ]
