# Generated by Django 2.0 on 2017-12-09 19:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0004_drop_verobose_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(blank=True, help_text='A 40-character key provided by ComicVine. This is used to retrieve metadata about your comics. You can create a ComicVine API Key at <a target="_blank" href="http://comicvine.gamespot.com/api/">ComicVine\'s API Page</a> (ComicVine account is required).',
                                             max_length=40, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length must be 40 characters.', regex='^.{40}$')], verbose_name='ComicVine API Key')),
                ('comics_directory', models.CharField(
                    blank=True, help_text='Directory where comic archives are located.', max_length=350, verbose_name='Comics Directory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
