# Generated by Django 2.0.1 on 2018-01-20 19:52

from django.db import migrations, models


def add_role_data(apps, schema_editor):
    Roles = apps.get_model('comics', 'Roles')
    Role = apps.get_model('comics', 'Role')

    for creator in Roles.objects.all():
        for role in creator.roles:
            role_obj, r_create = Role.objects.get_or_create(name=role.title())
            creator.role.add(role_obj)


def remove_role_data(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0005_add_role_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='role',
            field=models.ManyToManyField(to='comics.Role'),
        ),
        migrations.RunPython(
            add_role_data,
            remove_role_data
        ),
    ]
