# Generated by Django 2.0 on 2017-12-19 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0005_add_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='thumb',
            field=models.FilePathField(blank=True, path='media/images', verbose_name='Thumbnail file path'),
        ),
        migrations.AddField(
            model_name='creator',
            name='thumb',
            field=models.FilePathField(blank=True, path='media/images', verbose_name='Thumbnail file path'),
        ),
        migrations.AddField(
            model_name='team',
            name='thumb',
            field=models.FilePathField(blank=True, path='media/images', verbose_name='Thumbnail file path'),
        ),
    ]
