# Generated by Django 2.0 on 2017-12-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0006_add_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='thumb',
            field=models.FilePathField(blank=True, path='media/images', verbose_name='Thumbnail file path'),
        ),
    ]
