# Generated by Django 2.0.1 on 2018-01-20 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0006_roles_migrate_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roles',
            name='roles',
        ),
    ]
