# Generated by Django 2.0.2 on 2018-02-20 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0007_remove_roles_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='thumb',
        ),
        migrations.RemoveField(
            model_name='creator',
            name='thumb',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='thumb',
        ),
        migrations.RemoveField(
            model_name='team',
            name='thumb',
        ),
    ]
