# Generated by Django 2.0.1 on 2018-01-20 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0007_remove_roles_roles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Roles',
            new_name='Credits',
        ),
        migrations.AlterModelOptions(
            name='credits',
            options={'ordering': ['creator__name'], 'verbose_name_plural': 'Credits'},
        ),
    ]
