# Generated by Django 2.0.2 on 2018-02-21 21:14

import os

from django.conf import settings
from django.db import migrations, models


def fix_arc_location(apps, schema_editor):
    Arc = apps.get_model('comics', 'Arc')
    for arc in Arc.objects.all():
        if (arc.image):
            base_name = os.path.basename(arc.image.name)
            img = 'images/arcs/' + base_name
            old_path = settings.MEDIA_ROOT + '/' + str(arc.image.name)
            new_path = settings.MEDIA_ROOT + '/' + img
            arc.image = img
            arc.save()
            # Move the file
            os.rename(old_path, new_path)


def fix_character_location(apps, schema_editor):
    Character = apps.get_model('comics', 'Character')
    for character in Character.objects.all():
        if (character.image):
            base_name = os.path.basename(character.image.name)
            img = 'images/characters/' + base_name
            old_path = settings.MEDIA_ROOT + '/' + str(character.image.name)
            new_path = settings.MEDIA_ROOT + '/' + img
            character.image = img
            character.save()
            # Move the file
            os.rename(old_path, new_path)


def fix_creator_location(apps, schema_editor):
    Creator = apps.get_model('comics', 'Creator')
    for creator in Creator.objects.all():
        if (creator.image):
            base_name = os.path.basename(creator.image.name)
            img = 'images/creators/' + base_name
            old_path = settings.MEDIA_ROOT + '/' + str(creator.image.name)
            new_path = settings.MEDIA_ROOT + '/' + img
            creator.image = img
            creator.save()
            # Move the file
            os.renames(old_path, new_path)


def fix_issue_location(apps, schema_editor):
    Issue = apps.get_model('comics', 'Issue')
    for issue in Issue.objects.all():
        if (issue.cover):
            base_name = os.path.basename(issue.cover.name)
            img = 'images/issues/' + base_name
            old_path = settings.MEDIA_ROOT + '/' + str(issue.cover.name)
            new_path = settings.MEDIA_ROOT + '/' + img
            issue.cover = img
            issue.save()
            # Move the file
            os.renames(old_path, new_path)


def fix_publisher_location(apps, schema_editor):
    Publisher = apps.get_model('comics', 'Publisher')
    for publisher in Publisher.objects.all():
        if (publisher.logo):
            base_name = os.path.basename(publisher.logo.name)
            img = 'images/publishers/' + base_name
            old_path = settings.MEDIA_ROOT + '/' + str(publisher.logo.name)
            new_path = settings.MEDIA_ROOT + '/' + img
            publisher.logo = img
            publisher.save()
            # Move the file
            os.renames(old_path, new_path)


def fix_team_location(apps, schema_editor):
    Team = apps.get_model('comics', 'Team')
    for team in Team.objects.all():
        if (team.image):
            base_name = os.path.basename(team.image.name)
            img = 'images/teams/' + base_name
            old_path = settings.MEDIA_ROOT + '/' + str(team.image.name)
            new_path = settings.MEDIA_ROOT + '/' + img
            team.image = img
            team.save()
            # Move the file
            os.renames(old_path, new_path)


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0008_remove_thumbnail_fields'),
    ]

    operations = [
        migrations.RunPython(fix_arc_location),
        migrations.RunPython(fix_character_location),
        migrations.RunPython(fix_creator_location),
        migrations.RunPython(fix_issue_location),
        migrations.RunPython(fix_publisher_location),
        migrations.RunPython(fix_team_location),
        migrations.AlterField(
            model_name='arc',
            name='image',
            field=models.FileField(blank=True, upload_to='images/arcs/'),
        ),
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.FileField(blank=True, upload_to='images/characters/'),
        ),
        migrations.AlterField(
            model_name='creator',
            name='image',
            field=models.FileField(blank=True, upload_to='images/creators/'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='cover',
            field=models.FileField(
                blank=True, upload_to='images/issues/', verbose_name='Cover Image'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='logo',
            field=models.FileField(blank=True, upload_to='images/publishers/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.FileField(blank=True, upload_to='images/teams/'),
        ),
    ]
