# Generated by Django 2.0.3 on 2018-04-09 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0011_increase_imagefield_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name_plural': 'Settings'},
        ),
    ]
